FROM docker.osgeo.org/geoserver:2.23.0

LABEL maintainer="IGN"
LABEL version="0.1.0"

ADD data/web.xml /opt/apache-tomcat-9.0.68/webapps/geoserver/WEB-INF
  
ADD data/geoserver_data /opt/geoserver_data

 
